# Generated by Django 3.2.9 on 2023-06-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servisarg', '0002_consultareclamosugerencia_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultareclamosugerencia',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
    ]
